### ISSUE TITLE
Live wallpaper 

### ISSUE THREAD

**Issue by ScarletAndWolfie** [gios2/Walltaker-Changer#1]
It won't show the live wallpaper you get the option to set it when you press  start but when you go to set it black instead of the gif l,animated or video. 
![Screenshot_20231212_010019_Live Wallpaper Picker](https://github.com/gios2/Walltaker-Changer/assets/153585376/a7c0193f-7cf9-4bdb-83ca-92c5fcad008e)

**Comment by gios2** [comment]
What version of android do you have?

**Comment by ScarletAndWolfie** [comment]
> What version of android do you have?

I have android 13

**Comment by gios2** [comment]
Fixed in version 3.0.11
